---
version: v2.30.1-beta
slug: deconz
name: deCONZ-beta
description: >-
  Control a Zigbee network with ConBee or RaspBee by Dresden Elektronik
url: https://github.com/mattreim/hassio-addons/tree/main/deconz-beta
apparmor: false
arch:
  - amd64
  - armhf
  - aarch64
backup_exclude:
  - "*/otau"
devices:
  - /dev/mem
discovery:
  - deconz
gpio: true
homeassistant: 0.91.2
image: ghcr.io/mattreim/{arch}-addon-deconz-beta
ingress: true
ingress_entry: ingress.html
init: false
kernel_modules: true
options:
  device: null
panel_icon: mdi:zigbee
ports:
  40850/tcp: null
  5900/tcp: null
  8081/tcp: null
privileged:
  - SYS_RAWIO
schema:
  device: device(subsystem=tty)
  dbg_aps: int?
  dbg_info: int?
  dbg_otau: int?
  dbg_zcl: int?
  dbg_zdp: int?
startup: services
udev: true
usb: true
